### ISSUE TITLE
"This plugin has no configuration options" when looking for the plugin settings

### ISSUE THREAD

**Issue by szpak** [yurenchen000/terminator-autotheme-plugin#3]
It took me a minute to find where I can activate the plugin settings. Initially, I was looking for it in the plugin settings, but there is only "This plugin has no configuration options" displayed. In fact, I don't know if it is implemented in Terminator, as I have the aforementioned text for all the plugins... In the end, I have found it in the context menu, but I think, it could be mentioned in the README.

**Comment by yurenchen000** [comment]
sorry for that confuse.
i'll improve the README.

all terminaor plugin no configuration options
(cause terminator plugin not support that so far)
unless via some hack way..

ref:
https://gnome-terminator.readthedocs.io/en/latest/plugins.html

> The current plugins do not have configuration options in the [Plugins](https://gnome-terminator.readthedocs.io/en/latest/preferences.html#prefs-plugins) tab of the [Preferences Window](https://gnome-terminator.readthedocs.io/en/latest/preferences.html#preferences). The plugin architecture was created before I (Steve Boddy) became maintainer, and so far I haven’t had reason to figure out the detail. I’m not entirely sure if/how a plugin can add options to the configuration options in the [Plugins](https://gnome-terminator.readthedocs.io/en/latest/preferences.html#prefs-plugins) tab.

**Comment by yurenchen000** [comment]
I once wanted to do a hack implementation 
and had some clue

**Comment by szpak** [comment]
I see. That's why it looked weird for me seeing "This plugin has no configuration options" for all the plugins :).

**Comment by yurenchen000** [comment]
I have impelent it in a HACK way here
(for plugin customize configratoin page)

https://github.com/yurenchen000/terminator-plugin-ui
